### ISSUE TITLE
Google analytics

### ISSUE THREAD

**Issue by utam0k** [pseudorook/capsule#1]
I am using a capsule and favourite this theme.
It is cool.

By the way, I want to use "Google analystics" in this theme.
How about I do it?

Now I tried writeing "googleAnalytics: UA-123-45" in `config.yaml`.
And ran `hugo` command.
However, `public` folder nothing change.

**Comment by sudorook** [comment]
I have added support for analytics (91d072beffe91a90155da1cd55fbed23d2c66fe3). 

To enable it, add to the config.toml:
```
[params]
  googleAnalytics = "<your id>"
```
or whatever the yaml equivalent is.
