### ISSUE TITLE
.Next and .Prev are deprecated

### ISSUE THREAD

**Issue by CosmicToast** [pseudorook/capsule#2]
And will be removed.
Hugo reminds me of this on every build/change.

`.Prev` is meant to be replaced with `.NextPage`, and `.Next` with `.PrevPage` (they reversed it).

**Comment by sudorook** [comment]
Fixed in commit 3207ef747c6d50ca57607d6078df86e3c62872b5.

Guess the idea is to keep things consistent with `.NextInSection` and `.Paginator.Next`, etc....
